/vis/open
/vis/drawVolume twisted

/vis/viewer/set/auxiliaryEdge
/vis/viewer/set/lineSegmentsPerCircle 45
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 70 45

/vis/scene/add/axes 0 0 0 3 cm
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsColour magenta

/run/beamOn 10
