/control/verbose 2

/run/initialize

/geometry/test/run

/control/execute ../electron.mac

/vis/open
/vis/drawVolume ellipsoid

/control/execute ../vis.mac

/vis/verbose 0
/control/verbose 0
/control/doifBatch /control/execute ../tsg.mac

/control/shell if ls *.png 1>/dev/null 2>&1; then \
 ffmpeg -i "g4tsg_offscreen_zb_png_%d.png" -y ellipsoid.gif; fi
/control/shell if [ -f ellipsoid.gif ]; then rm -f *.png; fi

