/vis/viewer/set/style surface
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 60 0

/vis/scene/add/axes
/vis/scene/add/trajectories smooth
/vis/scene/endOfEventAction accumulate

/vis/modeling/trajectories/create/drawByParticleID
/vis/modeling/trajectories/drawByParticleID-0/set gamma magenta
/vis/modeling/trajectories/drawByParticleID-0/default/setDrawStepPts true
/vis/modeling/trajectories/drawByParticleID-0/default/setStepPtsColour white

/run/beamOn 10
