/control/verbose
/process/em/verbose 0
/process/had/verbose 0

/run/initialize

/vis/open
/vis/drawVolume 
/vis/viewer/refresh
/vis/scene/add/axes
/vis/scene/add/gps
/vis/scene/add/trajectories
/vis/scene/endOfEventAction accumulate

/gps/particle gamma
/gps/energy 1 keV
/gps/position -6 0 0 cm
/gps/direction 1 0 0

/tracking/verbose 2
/run/beamOn 10
/vis/viewer/refresh

/gps/energy 1 MeV
/run/beamOn 10
/vis/viewer/refresh