filetype: mac

detect:
  filename: "\\.macr?o?$"

rules:
  - constant.number: "\\b\\d*\\.?\\d*"
  - constant.boolen: "\\b(true|false)\\b"
  - symbol: "\\b(mm|cm|m|degree|deg|rad|eV|keV|MeV|GeV|TeV|tesla|T)\\b"
  - type: "\\b(alpha|gamma|e+|e-|mu+|mu-|neutron|proton|opticalphoton)\\b"
  - preproc: "\\b(surface|wireframe|cloud|perspective|orthogonal|accumulate|cam)"
  - preproc: "\\b(Scintillation|Cerenkov)\\b"
  - preproc: "\\bOp(Boundary|Absorption|Rayleigh|MieHG|WLS)\\b"
  - preproc: "\\b(Electromagnetic|Optical)\\b"
  - preproc: "\\b(iso)\\b"
  - preproc: "\\bFTFP_(BERT|INCLXX)(|_ATL|_HP|_TRV)\\b"
  - preprox: "\\bFTF(QGSP_BERT|_BIC)\\b"
  - preprox: "\\bQGSP_(BERT|BIC|INCLXX)(|_HP_AllHP|_HPT)\\b"
  - preprox: "\\b(NuBeam|QBBC|QGS_BIC|Shielding|ShieldingLEND|LBE|QBBC_ABLA)\\b"
  - preproc: "\\b(ATree|DAWNFILE|HepRepFile|RayTracer|VRML2FILE|gMocrenFile|TSG_OFFSCREEN|TSG_FILE|OGLIQt|OGLI|OGLSQt|OGL|OGLS|OGLIX|OGLIQt_FALLBACK|OGLSX|OGLSQt_FALLBACK|RayTracerX|Qt3D|TSG_X11_GLES|TSGX11|TSG_QT_GLES_FALLBACK|TSG_X11_ZB|TSGX11ZB|TSG_QT_GLES|TSGQt|TSG|TSG_QT_ZB|TSGQtZB|Vtk)\\b"
  - preproc: "\\b(aquamarine|black|blue|blueviolet|brown|cadetblue|coral|cornflowerblue|cyan|darkgreen|darkolivegreen|darkorchid|darkslateblue|darkslategrey|darkturquoise|dimgrey|firebrick|forestgreen|gold|goldenrod|gray|green|greenyellow|grey|indianred|khaki|lightblue|lightgrey|lightsteelblue|limegreen|magenta|maroon|mediumaquamarine|mediumblue|mediumorchid|mediumseagreen|mediumslateblue|mediumspringgreen|mediumturquoise|mediumvioletred|midnightblue|navy|navyblue|orange|orangered|orchid|palegreen|pink|plum|red|salmon|seagreen|sienna|skyblue|slateblue|springgreen|steelblue|tan|thistle|turquoise|violet|violetred|wheat|white|yellow|yellowgreen)\\b"
  - identifier: "^/(control|units|analysis|praticle|tracking|geometry|process|event|cuts|run|random|material|physics_lists|gps|gun|grdm|score|vis|physics_engine)/[a-zA-Z/]+\\b"
  - comment: "#.*$"
