/control/verbose

/process/em/verbose 0
/process/had/verbose 0

/run/initialize

/geometry/test/run

/control/execute ../gamma.mac

/vis/open
/vis/drawVolume polycone1

/control/execute ../vis.mac

/vis/verbose 0
/control/verbose 0
/control/doifBatch /control/execute ../tsg.mac

/control/shell if ls *.png 1>/dev/null 2>&1; then \
 ffmpeg -i "g4tsg_offscreen_zb_png_%d.png" -y polycone.gif; fi
/control/shell if [ -f polycone.gif ]; then rm -f *.png; fi

