#/control/execute ../vis.mac

/vis/open TSG_FILE
/vis/drawVolume box
/vis/scene/add/axes
/vis/viewer/set/upVector 0 0 1
/vis/viewer/set/viewpointThetaPhi 60 120
/control/loop ../phi.mac phi 120 260 1

/control/shell if [ -f G4Data0.heprep ]; then mv G4Data0.heprep tubs.heprep; fi
/control/shell if [ -f g4_00.wrl ]; then mv g4_00.wrl tubs.wrl; fi
/control/shell if ls *.png 1>/dev/null 2>&1; then magick convert *.png box.gif; fi

